export const FEATURE_LIST = [
  "zikaze_bakaze_toitu",
  "kaze_toitu",
  "sangen_toitu",
  "zi_toitu",
  "ichikyu_toitu",
  "chunchan_toitu",
  "zikaze_bakaze_kotu",
  "kaze_kotu",
  "sangen_kotu",
  "zi_kotu",
  "ichikyu_kotu",
  "chunchan_kotu",
  "zikaze_bakaze_kantu",
  "kaze_kantu",
  "sangen_kantu",
  "zi_kantu",
  "ichikyu_kantu",
  "chunchan_kantu",
  "ichikyu_shuntu",
  "chunchan_shuntu",
  "penchan",
  "3-7_ryanmen",
  "23_78_ryanmen",
  "13_79_kanchan",
  "2-8_kanchan",
  "zikaze_bakaze_cnt",
  "kaze_cnt",
  "sangen_cnt",
  "zi_cnt",
  "ichikyu_cnt",
  "chunchan_cnt",
  "same_color_cnt",
  "1-9_cnt",
  "ittu_cnt",
  "sanshoku_cnt",
  "sanshoku_mentu",
  "chitoitu_cnt",
  "toitoi_sananko_cnt",
  "kokushi_cnt",
];

export const TYPE_LIST = {
  m: 0,
  p: 1,
  s: 2,
  w: 3,
  z: 4,
};
