export const DIMENSIONS = [
  "tanyao",
  "pinfu",
  "ittu",
  "honitu",
  "chinitu",
  "junchan",
  "chanta",
  "sangenhai",
  // "honroto",
  "shosangen",
  "sananko",
  "zikaze_bakaze",
  "ipeko",
  // "ryanpeko",
  "chitoitu",
  "sanshoku_dojun",
];
