export const YAKU_DESCRIPTION = {
  zikaze_bakaze: {
    name: "自風場風",
    description: "自風または場風の字牌を3枚揃える",
    han: 1,
    kuiHan: 1,
    menzen: false,
  },
  sangenhai: {
    name: "三元牌",
    description: "「白」、「發」、「中」のいずれかの刻子を揃える",
    han: 1,
    kuiHan: 1,
    menzen: false,
  },
  tanyao: {
    name: "タンヤオ",
    description: "数牌の2~8牌のみで揃える",
    han: 1,
    kuiHan: 1,
    menzen: false,
  },
  pinfu: {
    name: "平和",
    description:
      "順子が4つ、頭が役牌以外、待ちが両面待ちであることを満たすと成立する",
    han: 1,
    kuiHan: 1,
    menzen: true,
  },
  sanshoku_dojun: {
    name: "三色同順",
    description: "順子を3種類ともすべて同じ数で揃える",
    han: 2,
    kuiHan: 1,
    menzen: false,
  },
  sanshoku_doko: {
    name: "三色同刻",
    description: "数牌の刻子を3種類とも同じ数字で揃える",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  ittu: {
    name: "一気通貫",
    description: "「123、456、789」の面子を揃える",
    han: 2,
    kuiHan: 1,
    menzen: false,
  },
  chitoitu: {
    name: "七対子",
    description: "対子を7種類揃える（但し、同じ牌4枚では成立しない）",
    han: 2,
    kuiHan: 2,
    menzen: true,
  },
  // toitoiho: {
  //   name: "対々和",
  //   description: "刻子のみで揃える",
  //   han: 2,
  //   kuiHan: 2,
  //   menzen: false,
  // },
  sananko: {
    name: "三暗刻",
    description: "暗刻を3つ揃える",
    han: 2,
    kuiHan: 2,
    menzen: true,
  },
  chanta: {
    name: "チャンタ",
    description: "数牌の1か9の牌が含まれる順子、刻子と字牌の刻子で揃える",
    han: 2,
    kuiHan: 1,
    menzen: false,
  },
  junchan: {
    name: "純チャン",
    description: "数牌の1か9の牌が含まれる順子、刻子を揃える",
    han: 3,
    kuiHan: 2,
    menzen: false,
  },
  honroto: {
    name: "混老頭",
    description: "1か9、字牌のみの刻子で揃える",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  // sankantu: {
  //   name: "三槓子",
  //   description: "槓子を3つ揃える",
  //   han: 2,
  //   kuiHan: 2,
  //   menzen: false,
  // },
  shosangen: {
    name: "小三元",
    description:
      "「白」、「發」、「中」の中で、2種類を刻子、残り1種類を頭で揃える",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  ipeko: {
    name: "一盃口",
    description: "同じ種類且つ同じ数字の順子を二つ揃える",
    han: 1,
    kuiHan: 1,
    menzen: true,
  },
  ryanpeko: {
    name: "二盃口",
    description:
      "同じ種類且つ同じ数字の順子が二つ揃い、且つそれを2種類揃える",
    han: 3,
    kuiHan: 3,
    menzen: true,
  },
  honitu: {
    name: "混一色",
    description: "数牌の3種類のうちどれか1種類の牌種と字牌のみで揃える",
    han: 3,
    kuiHan: 2,
    menzen: false,
  },
  chinitu: {
    name: "清一色",
    description: "数牌の3種類のうちどれか1種類の牌種のみで揃える",
    han: 6,
    kuiHan: 5,
    menzen: false,
  },
};
