export const YAKU_DESCRIPTION = {
  zikaze_bakaze: {
    name: "自風場風",
    description: "自分の風または場の風の字牌を3枚揃えると成立する",
    han: 1,
    kuiHan: 1,
    menzen: false,
  },
  sangenhai: {
    name: "三元牌",
    description: "「白」、「發」、「中」のいずれかが3枚揃うと成立する",
    han: 1,
    kuiHan: 1,
    menzen: false,
  },
  tanyao: {
    name: "タンヤオ",
    description: "2～8の牌のみで揃えると成立する（字牌も含まない）",
    han: 1,
    kuiHan: 1,
    menzen: false,
  },
  pinfu: {
    name: "平和",
    description:
      "連番でそろえたまとまりが４つ、頭が数牌、待ちが２種類以上のすべてをそろえると成立する",
    han: 1,
    kuiHan: 1,
    menzen: true,
  },
  ipeko: {
    name: "一盃口",
    description: "同じ数の牌で同じ連番のまとまりが二つ揃うと成立する",
    han: 1,
    kuiHan: 1,
    menzen: true,
  },
  sanshoku_dojun: {
    name: "三色同順",
    description: "連番のまとまりを3種類ともすべて同じ数で揃えると成立する",
    han: 2,
    kuiHan: 1,
    menzen: false,
  },
  sanshoku_douko: {
    name: "三色同刻",
    description: "同じ牌を3つ揃えたまとまりを3種類同じ数字で揃えると成立する",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  sananko: {
    name: "三暗刻",
    description: "自分のみで同じ牌を3つ揃えたまとまりを3種類揃えると成立する",
    han: 2,
    kuiHan: 2,
    menzen: true,
  },
  ittu: {
    name: "一気通貫",
    description: "「123、456、789」をどれかの種類で揃えると成立する",
    han: 2,
    kuiHan: 1,
    menzen: false,
  },
  chitoitu: {
    name: "七対子",
    description: "同じ牌を2つ揃えたまとまりが7種類揃うと成立する",
    han: 2,
    kuiHan: 2,
    menzen: true,
  },
  toitoiho: {
    name: "対々和",
    description: "",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  chanta: {
    name: "チャンタ",
    description: "1か9の牌が含まれるまとまりと字牌で揃えると成立する",
    han: 2,
    kuiHan: 1,
    menzen: false,
  },
  sankantu: {
    name: "三槓子",
    description: "自分でカンを3回鳴くと成立する",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  shousangen: {
    name: "小三元",
    description:
      "「白」、「發」、「中」の中で、2種類を3つ、残り1種類を2つ（頭で）揃えると成立する",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  honroto: {
    name: "混老頭",
    description: "1か9の牌のみと字牌で揃えると成立する",
    han: 2,
    kuiHan: 2,
    menzen: false,
  },
  ryanpeko: {
    name: "二盃口",
    description:
      "同じ数の牌で同じ連番のまとまりが二つ揃い、且つそれが2種類揃うと成立する",
    han: 3,
    kuiHan: 3,
    menzen: true,
  },
  junchan: {
    name: "純チャン",
    description: "すべての牌を1と9の牌のみで揃えると成立する",
    han: 3,
    kuiHan: 2,
    menzen: false,
  },
  honitu: {
    name: "混一色",
    description: "3種類のうちどれか1種類の牌と字牌のみで揃えると成立する",
    han: 3,
    kuiHan: 2,
    menzen: false,
  },
  chinitu: {
    name: "清一色",
    description: "3種類のうちどれか1種類の牌のみで揃えると成立する",
    han: 6,
    kuiHan: 5,
    menzen: false,
  },
};
